# Change these first
owner: edbighead # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Laur
    url: https://laur.work/


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  zcname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  zintroMessage: This is a status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/edbighead/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
